#!/usr/bin/env bash

set -e
set -x

# XXX: hacky
version=`grep '^  "version"' package.json | sed -e 's/^  "version": "\(.*\)".*$/\1/'`

# ensure we have no unstaged changes
git diff --exit-code --quiet # TODO: report error

npm test

# selectively determine package contents
mkdir tmp_pub
git ls-tree --name-only HEAD | while read filename; do
	cp -r "$filename" tmp_pub
done
cd tmp_pub
mv src/* ./
rm -r src

echo "about to publish v${version}"
read -n1 -p "enter 'y' to continue" confirmation
if [ "$confirmation" = "y" ]; then
	npm publish
	cd ..
	git tag "v${version}"
	git push --tags origin master
else
	cd ..
fi
rm -r tmp_pub
